
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Picture_development
test:
  <<: *default
  database: Picture_test
production:
  <<: *default
  database: Picture_production