
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 12201995
  host: db

development:
  <<: *default
  database: Picture_development

  
test:
  <<: *default
  database: Picture_test

production:
  <<: *default
  database: Picture_production
  username: Picture
  password: <%= ENV['PICTURE_DATABASE_PASSWORD'] %>
