
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12201995
  host: 172.20.0.2
  url: <%= ENV["DATABASE_URL"]%>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

  test:
  <<: *default

production:
  <<: *default