version: '2'
services:
  db:
    image: postgres
    restart: always
  app:
    stdin_open: true
    tty: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Picture
    ports:
      - "3000:3000"
    depends_on:
      - db