version: '3'
services:
  app_api:
    build: ./app_api
    container_name: app_api
    links:
      - db
    volumes:
      - ./app_api:/webapp
    ports:
      - "3001:3001"
    command: sh /webapp/entry.sh
  db:
    image: postgres
    restart: always
